blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.RegisterFormView.as_view(), name="register"),
    path('posts/', views.PostListView.as_view(), name='posts'),
    path('posts/<int:pk>', views.PostDetailView.as_view(), name='post-detail'),
    path('posts/create/', views.CreatePost.as_view(), name='create-post'),
    path('mycomments/', views.MyCommentView.as_view(), name='my-comments'),
    path('comment/create/<int:pk>', views.CommentCreateView.as_view(), name='create-comment'),
    path('profiles/<int:pk>/', views.ProfileInfo.as_view(), name='user-detail'),
    path('profiles/', views.ProfileList.as_view(), name='profile-list'),
    path('contact/', views.MessageAdmin.as_view(), name='message-admin'),
    path('profiles/<int:pk>/update/', views.UserEditView.as_view(), name='user-update'),
    path('password_reset_confirm/<int:pk>', views.BloggerPasswordChangeView.as_view(), name='password_reset_confirm'),
    path('profiles/<int:pk>/', views.ProfileInfo.as_view(), name='profile-list'),
]

blog_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', RedirectView.as_view(url='/blog/', permanent=True)),
    path('__debug__/', include('debug_toolbar.urls')),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=250)
    brief_description = models.CharField(max_length=250)
    full_description = models.CharField(max_length=500)
    image = models.ImageField(null=True, blank=True)
    posted = models.BooleanField(default=False)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    username = models.CharField(max_length=250, default='David')
    text = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    posted_com = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class UserUrl(User):

    def get_absolute_url(self):
        return reverse('user-detail', kwargs={'pk': self.pk})

blog/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from blog.models import Comment, Post

User = get_user_model()


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name']


class PostCreate(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'brief_description', 'full_description', 'posted']


class CommentCreate(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text', 'posted_com']


class ContactUsForm(forms.Form):
    text = forms.CharField(max_length=400, help_text="Describe your problem")

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data


class UserUpdate(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]

blog/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.decorators.cache import cache_page

from blog.forms import RegisterForm, ContactUsForm
from blog.models import Comment, Post, User

from blog.tasks import new_comment, send_mail_to_admin


def index(request):
    num_posts = Post.objects.count()
    num_comments = Comment.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(
        request,
        'blog/index.html',
        context={'num_posts': num_posts, 'num_comments': num_comments,
                 'num_visits': num_visits},
    )


class RegisterFormView(generic.FormView):
    template_name = 'registration/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        form.save()

        username = self.request.POST['username']
        password = self.request.POST['password1']

        user = authenticate(username=username, password=password)
        login(self.request, user)
        return super(RegisterFormView, self).form_valid(form)


class UserEditView(LoginRequiredMixin, generic.UpdateView):
    model = User
    fields = ["username", "first_name", "last_name", "email"]
    template_name = 'blog/update_user.html'
    success_url = reverse_lazy('index')

    def get_object(self, queryset=None):
        user = self.request.user
        return user


class PostListView(generic.ListView):
    model = Post
    paginate_by = 20
    template_name = 'blog/post_list.html'


@method_decorator(cache_page(30), name='dispatch')
class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'


class CreatePost(LoginRequiredMixin, SuccessMessageMixin, generic.CreateView):
    model = Post
    success_message = 'Author was created'
    template_name = "blog/create_post.html"
    fields = ('title', 'brief_description', 'full_description', 'image', 'posted')

    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        post.save()
        # text = 'Create new post'
        # send_mail_to_admin.delay(text)
        send_mail('Post', 'Create new post', 'david@example.com', ['admin@example.com'], fail_silently=False, )
        return super(CreatePost, self).form_valid(form)


class MyCommentView(LoginRequiredMixin, generic.ListView):
    model = Comment
    template_name = 'blog/my_comments.html'
    paginate_by = 10

    def get_queryset(self):
        return Comment.objects.filter(username=self.request.user).filter(posted_com=True)


class CommentCreateView(SuccessMessageMixin, generic.CreateView):
    template_name = 'blog/create_comment.html'
    model = Comment
    fields = ('username', "text", 'post')
    success_message = 'Comment was created'

    def get_success_url(self):
        return reverse('post-detail', kwargs={'pk': self.object.post.pk})

    def get_initial(self):
        post = get_object_or_404(Post, id=self.kwargs['pk'])
        return {
            'post': post
        }

    def form_valid(self, form):
        # message = 'Create new comment'
        # new_comment.delay(message)
        send_mail('Comment', 'Create new comment', 'david@example.com', ['admin@example.com'], fail_silently=False, )
        return super(CommentCreateView, self).form_valid(form)


class ProfileInfo(generic.DetailView):
    model = User
    template_name = "blog/profile_info.html"

    def get_context_data(self, **kwargs):
        if self.request.user == self.get_object():
            object_list = Post.objects.filter(author=self.get_object())
            context = super(ProfileInfo, self).get_context_data(object_list=object_list, **kwargs)
        else:
            object_list = Post.objects.filter(author=self.get_object())
            context = super(ProfileInfo, self).get_context_data(object_list=object_list, **kwargs)
        return context


@method_decorator(cache_page(30), name='dispatch')
class ProfileList(generic.ListView):
    queryset = User.objects.all()
    template_name = "blog/profile_list.html"


class MessageAdmin(SuccessMessageMixin, generic.FormView):
    form_class = ContactUsForm
    success_message = 'Message was send'
    success_url = reverse_lazy('index')
    template_name = 'blog/contact_us.html'

    def form_valid(self, form):
        data = form.cleaned_data
        send_mail('MESSAGE', data['text'], 'admin@gmail.com', ['example@gmail.com'], fail_silently=False, )
        return super(MessageAdmin, self).form_valid(form)


class BloggerPasswordChangeView(SuccessMessageMixin, PasswordChangeView):
    success_message = 'Password successfully changed'
    template_name = 'registration/password_reset_confirm.html'

    def get_success_url(self):
        return reverse('index')

blog/templates/blog/contact_us.html
{% extends 'base_generic.html' %}

{% block content %}
    <p>Write to us:</p>
    <form action="" method="post">
        <table>
            {% csrf_token %}
            {{ form.as_p }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

blog/templates/blog/create_comment.html
{% extends 'base_generic.html' %}

{% block content %}
    <p>Post your comment for: <a href="{{post.get_absolute_url}}">{{ post }}</a></p>
    <div class="container"></div>
    <form action="" method="post">
        <table>
            {% csrf_token %}
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>

{% endblock %}

blog/templates/blog/create_post.html
{% extends 'base_generic.html' %}
{% block content %}

    <h3>Create post:</h3>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add">
    </form>

{% endblock %}

blog/templates/blog/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Blog</h1>


  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Posts:</strong> {{ num_posts }}</li>
    <li><strong>Comments:</strong> {{ num_comments }}</li>
  </ul>

    <p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

{% endblock %}

blog/templates/blog/my_comments.html
{% extends 'base_generic.html' %}

{% block content %}
    <h3>Your Comments:</h3>

    {% if comment_list %}
    <ul>

      {% for comment in comment_list %}
      <li>
        {{ comment.text }}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>You haven't left any comments yet.</p>
    {% endif %}


{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Post title: {{ post.title }}</h1>
<style>
.raz div {
  min-height: 2em;
  margin-right: 0em;
  border: 1px solid black;
  background: #e6e6fa;
}
</style>

  <p><strong>Author:</strong> {{ post.author }}</p>
  <p><strong>Brief description:</strong> {{ post.brief_description }}</p>
  {% if post.image %}
       <img style="width: 200px; height: 250px;" src="{{ post.image.url }}" alt="#">
    {% endif %}
  <p><strong>Full description:</strong> {{ post.full_description }}</p>
<p>
<div>

        {% for comment in object.comment_set.all %}
             {% if comment.posted_com == True %}
        <ul>
                        <div><p><strong>Comments:</strong>
                        <p>{{ comment.username }} {{ comment.text }}</p>
        </ul>
                  {% else%}

            {% endif %}
        {% endfor %}
  <li class="nav-item">
                <a class="btn btn-outline-dark" href="{% url 'create-comment' post.pk %}?blog_id={{ post.id }}">Make comments</a>
            </li>
  </div>
</div>

{% endblock %}

blog/templates/blog/post_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Post List</h1>

    {% if post_list %}
    <ul>

      {% for post in post_list %}
      <li>
        <a href="{% url 'post-detail' post.pk %}">{{ post.title }}</a> ({{post.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no posts in the blog.</p>
    {% endif %}
{% endblock %}}

blog/templates/blog/profile_info.html
{% extends 'base_generic.html' %}
{% block content %}


    <div class="container">
        <strong>User Name: {{ user.username }}</strong>
        <strong><br>First Name: {{ user.first_name }}</strong>
        <strong><br>Last Name: {{ user.last_name }}</strong>

    </div>
   <h4>Post list</h4>
      {% for blog in object_list %}
        <div class="container-sm-2">
           <h4><a href="{{ blog.get_absolute_url }}">{{ blog.title|title }}</a></h4>
                {% endfor %}
            </div>
{% endblock %}

blog/templates/blog/profile_list.html
{% extends 'base_generic.html' %}
{% block content %}
<div style="display: flex; flex-direction: row; align-items: center">
        <h1>All Profiles</h1>
    </div>

    {% if user_list %}
    <ul>
      {% for profile in user_list %}
      <li>
          <p><a href="{% url 'user-detail' profile.pk %}">{{ profile.username }}</a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>There are no profiles.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/update_user.html
{% extends "base_generic.html" %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        <div class="content" style="display: flex; flex-direction: column; align-items: flex-start">
            {% csrf_token %}
            {{ form.as_p }}
        </div>

        <input type="submit" value="Submit">
    </form>
{% endblock content %}